### ISSUE TITLE
unique array

### ISSUE THREAD

**Issue by luwes** [ungap/set#2]
Awesome polyfill!

One thing that didn't work on my end in polyfilled IE11 was this little snippet to get a unique array back

```js
export function uniqueArray(array) {
    return [...new Set(array)];
}
```

**Comment by WebReflection** [comment]
IE11 has no Symbol.iterator, or no Symbol at all ... but it’s not clear what’s not working, how you are transpiling, if you are transpiriling, etc

**Comment by zloirock** [comment]
You could try `[...new Set(array).values()]`, in some transpiling cases it could help.

**Comment by zloirock** [comment]
However, I'm not sure that missed `.values` method is covered by feature detection.

**Comment by luwes** [comment]
ah yes, that might be it. the iterator missing on Set. good call!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/@@iterator

@zloirock thanks for the suggestion, pretty sure that would've worked because I had the Array iterator polyfilled.

thanks all!
